from numpy import exp

EXCESS_WEIGHT = 1.0
DISJOINT_WEIGHT = 1.0
WEIGHT_DIFFERENCE_WEIGHT = 0.4

COMPTABILITY_THRESHOLD = 3.0

PERTRUBE_WEIGHT_PROB = 0.9
RANDOM_WEIGHT_PROB = 0.1

WEIGHT_CAP = 1.0
WEIGHT_MUTATION_POWER = WEIGHT_CAP/10

DISABLE_PROB_IF_PARENT_DISABLED = 0.75

ADD_CONNECTION_MUTATION_ATTEMPTS = 20
ADD_NODE_MUTATION_ATTEMPTS = 20

PERCENT_NO_CROSSOVER = 0.25

INTERSPECIES_MATING_RATE = 0.001

POPULATION_SIZE = 100
MAX_GENERATIONS = 100

STAGNANT_SPECIES_AGE_DIFF = 15
SURVIVAL_THRESHOLD = 0.5

MUTATE_WEIGHTS_PROB = 0.8
MUTATE_TOGGLE_ENABLE_PROB = 0.1
MUTATE_RENABLE_PROB = 0.05
MUTATE_ADD_NODE_PROB = 0.03
MUTATE_DELETE_NODE_PROB = 0.01
MUTATE_ADD_LINK_PROB = 0.1
MUTATE_DELETE_LINK_PROB = 0.1

MATE_ONLY_PROB = 0.2


def sigmoid(x):
    return 1/(1 + exp(-4.9*x))