from numpy import exp

EXCESS_WEIGHT = 1.0
DISJOINT_WEIGHT = 1.0
WEIGHT_DIFFERENCE_WEIGHT = 0.4

COMPTABILITY_THRESHOLD = 3.0

STAGNANT_GENERATIONS_UNTIL_WIPE = 15

WEIGHT_MUTATION_PROB = 0.8
PERTRUBE_WEIGHT_PROB = 0.9
RANDOM_WEIGHT_PROB = 0.1

WEIGHT_CAP = 1.0
WEIGHT_MUTATION_POWER = WEIGHT_CAP/10


DISABLE_PROB_IF_PARENT_DISABLED = 0.75

ADD_CONNECTION_MUTATION_ATTEMPTS = 20
ADD_NODE_MUTATION_ATTEMPTS = 20

PERCENT_NO_CROSSOVER = 0.25

INTERSPECIES_MATING_RATE = 0.001

POPULATION_SIZE = 150
MAX_GENERATIONS = 100

SPECIES_PENALIZE_AGE = 15
SPECIES_STAGNANT_PENALTY = 0.01
SURVIVAL_THRESHOLD = 0.4

# define what is smaller larger population ?

SMALL_MUTATE_CONNCETION_PROB = 0.05
SMALL_MUTATE_NODE_PROB = 0.03

LARGE_MUTATE_CONNCETION_PROB = 0.3



def sigmoid(x):
    return 1/(1 + exp(-4.9*x))